build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "ffmpeg"
  python_packages:
    - "accelerate==0.26.1"
    - "torch==2.1.2"
    - "torchvision==0.16.2"
    - "torchaudio==2.1.2"
    - "pydub==0.25.1"
    - "pyannote.audio==3.1.1"
